# base settings MPlus API
baseurl: "https://mpbernmfk.zetcom.app/"

# MPlus API request definitions
image-search:
  type: "POST"
  url: "ria-ws/application/module/Multimedia/search"
  headers: 
    Content-Type: "application/xml"
    Accept: "application/xml"
  xml-body: "config/MultimediaSearch.xml"

image-search-downloadable:
  type: "POST"
  url: "ria-ws/application/module/Multimedia/search"
  headers:
    Content-Type: "application/xml"
    Accept: "application/xml"
  xml-body: "config/MultimediaSearchDownload.xml"

image-search-not-downloadable:
  type: "POST"
  url: "ria-ws/application/module/Multimedia/search"
  headers:
    Content-Type: "application/xml"
    Accept: "application/xml"
  xml-body: "config/MultimediaSearchNoDownload.xml"

image-download:
  type: "GET"
  url: "ria-ws/application/module/Multimedia/{id}/thumbnail?size={size}"
  headers:
    Content-Type: "application/octet-stream"

object-count:
  type: "POST"
  url: "ria-ws/application/module/Object/search"
  headers:
    Content-Type: "application/xml"
    Accept: "application/xml"
  xml-body: "config/ObjectCount.xml"

object-export:
  type: "POST"
  url: "ria-ws/application/module/Object/export/68013"
  headers:
    Content-Type: "application/xml"
  xml-body: "config/ObjectExport.xml"
